# Generated by Django 3.2.8 on 2021-10-22 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AuthModule', '0003_user_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
