# Generated by Django 4.0.4 on 2022-05-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthModule', '0004_alter_user_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
